import type { ComputedRef, Ref } from "vue";
import type { OutputOption } from "../../data/outputOptions";
import { useGalleryStore, type GalleryFlatItem } from "../../stores/gallery";
import { useJobStore, type JobSummary } from "../../stores/jobs";
import { usePromptStore, type SavedPrompt } from "../../stores/prompts";
import { useProviderStore } from "../../stores/provider";
import { useWorkspaceStore, type WorkflowName } from "../../stores/workspace";
import type { FailurePopupState } from "./failurePopup";
import type { RuntimeLightboxState } from "./lightbox";
import type { LoadModelsOptions, ModelOption, ModelPickerStatus, ModelPickerTone, ProviderFormState } from "./providerModelPicker";
import type { SourceImageItem, SourceImageReference } from "./sourceImages";
import type { StatusTone } from "./status";
import type { RuntimeWorkspaceForm } from "./workspacePersistence";

export type RuntimeLightboxItem = GalleryFlatItem;

export interface RuntimeModelPickerState {
  loading: boolean;
  message: string;
  messageTone: ModelPickerTone;
  options: ModelOption[];
  hasLoaded: boolean;
  status: ModelPickerStatus;
  loadedSignature: string;
}

export interface ScimageRuntimePublicApi {
  addSourceFiles: (files: Iterable<File>) => void;
  addSourceImageFromGallery: (item: GalleryFlatItem) => Promise<void>;
  addSourceImageFromUrl: (source: SourceImageReference, successMessage?: string, duplicateMessage?: string) => Promise<void>;
  activateProviderProfile: (profileId: string) => Promise<void>;
  applyPrompt: (prompt: SavedPrompt) => void;
  appendPromptToken: (token: string) => void;
  batchDelete: () => Promise<void>;
  batchDownload: () => Promise<void>;
  busyJobIds: Ref<Set<string>>;
  canGenerate: ComputedRef<boolean>;
  cleanupEmptyGeneratedDirs: () => Promise<void>;
  closeFailurePopup: () => void;
  clearPrompts: () => Promise<void>;
  clearSelection: () => void;
  clearSourceImages: () => void;
  clockTick: Ref<number>;
  closeLightbox: () => void;
  currentLightboxItem: ComputedRef<RuntimeLightboxItem | null>;
  currentWorkflowForm: ComputedRef<RuntimeWorkspaceForm>;
  deleteImage: (jobId: string, slot: number, context?: Record<string, unknown>) => Promise<void>;
  deleteLightboxItem: () => Promise<void>;
  deletePrompt: (id: string) => void;
  deleteProviderProfile: (profileId: string) => Promise<void>;
  downloadItem: (item: GalleryFlatItem) => Promise<void>;
  failurePopup: FailurePopupState;
  forms: Record<WorkflowName, RuntimeWorkspaceForm>;
  galleryStore: ReturnType<typeof useGalleryStore>;
  generate: () => Promise<unknown>;
  initRuntime: () => Promise<void>;
  isActiveStatus: (status: string) => boolean;
  isCleaningGeneratedDirs: Ref<boolean>;
  isCreatingJob: Ref<boolean>;
  isRetryableJob: (job: JobSummary | null | undefined) => boolean;
  jobAction: (jobId: string, action: "cancel" | "retry" | "delete") => Promise<void>;
  jobStore: ReturnType<typeof useJobStore>;
  lightbox: RuntimeLightboxState;
  lightboxItems: ComputedRef<RuntimeLightboxItem[]>;
  loadModels: (options?: LoadModelsOptions) => Promise<void>;
  loadMoreGallery: () => Promise<void>;
  loadMoreJobs: () => Promise<void>;
  modelPicker: RuntimeModelPickerState;
  navLightbox: (direction: number) => void;
  openLightbox: (index: number) => void;
  openLightboxFromItems: (items: GalleryFlatItem[], index: number) => void;
  providerCanLoadModels: ComputedRef<boolean>;
  providerCanSaveAs: ComputedRef<boolean>;
  providerCanSaveCurrent: ComputedRef<boolean>;
  providerForm: ProviderFormState;
  providerSaveBlockMessage: ComputedRef<string>;
  providerStore: ReturnType<typeof useProviderStore>;
  providerWorkflowAvailability: ComputedRef<Record<WorkflowName, boolean>>;
  promptStore: ReturnType<typeof usePromptStore>;
  qualityOptions: ComputedRef<OutputOption[]>;
  refreshJobs: (options?: { silent?: boolean; reset?: boolean; manual?: boolean }) => Promise<void>;
  removePromptToken: (token: string) => void;
  removeSourceImage: (key: string) => void;
  resetFormState: () => void;
  resolveGalleryTerminalAction: (item: GalleryFlatItem) => Promise<void>;
  savePrompt: () => void;
  saveProviderProfile: (saveAsNew?: boolean) => Promise<void>;
  selectByRect: (rect: DOMRect) => void;
  setGalleryFilter: (filter: "all" | "tasks" | "prompts") => void;
  setStatus: (tone: StatusTone, message: string, timeoutMs?: number) => void;
  setWorkflow: (workflow: WorkflowName) => boolean;
  sizeOptions: ComputedRef<OutputOption[]>;
  sourceImages: Ref<SourceImageItem[]>;
  status: {
    tone: StatusTone;
    message: string;
  };
  togglePromptToken: (token: string) => void;
  toggleSelection: (item: GalleryFlatItem) => void;
  toggleSort: () => void;
  visibleGalleryItems: ComputedRef<GalleryFlatItem[]>;
  workspaceStore: ReturnType<typeof useWorkspaceStore>;
}
