import os

from runtime_paths import RUNTIME_PATHS

HOST = "127.0.0.1"
PORT = 8765
MAX_IMAGE_COUNT = 6
MAX_SOURCE_IMAGE_COUNT = 16
MAX_SOURCE_IMAGE_BYTES = 50 * 1024 * 1024
RECENT_JOBS_LIMIT = 60

APP_ROOT = RUNTIME_PATHS.resource_root
STATIC_DIR = RUNTIME_PATHS.static_dir
GENERATED_DIR = RUNTIME_PATHS.generated_dir
LOCAL_STATE_DIR = RUNTIME_PATHS.local_state_dir
PROVIDER_PROFILES_PATH = RUNTIME_PATHS.provider_profiles_path
JOB_RECORDS_PATH = RUNTIME_PATHS.job_records_path
WORKSPACE_STATE_PATH = RUNTIME_PATHS.workspace_state_path
DEFAULT_PROVIDER_MODEL = os.getenv("IMAGE_API_MODEL", "gpt-image-2")
