from __future__ import annotations

from output_profiles import (
    API_EDGE_MULTIPLE,
    API_MAX_EDGE,
    API_MAX_PIXELS,
    API_MIN_PIXELS,
    ASPECT_LABELS,
    ASPECT_SIZE_OPTIONS,
    ASPECT_SIZE_OPTIONS_WITH_AUTO,
    AUTO_OPTION,
    DEFAULT_OUTPUT_PROFILE_ID,
    DEFAULT_QUALITY,
    DEFAULT_SIZE_OPTION,
    OPENAI_SDK_IMAGE_QUALITY_MAP,
    OUTPUT_PROFILE_ASPECT_V1,
    OUTPUT_PROFILE_PIXEL_V1,
    PIXEL_SIZE_BY_ASPECT_AND_QUALITY,
    PIXEL_SIZE_OPTION_MAP,
    PIXEL_SIZE_OPTIONS_BY_QUALITY,
    PIXEL_TIER_LONG_EDGE_MAX,
    QUALITY_4K,
    QUALITY_ALIASES_BY_PROFILE,
    QUALITY_HD,
    QUALITY_HIGH,
    QUALITY_LABELS_BY_PROFILE,
    QUALITY_LOW,
    QUALITY_MEDIUM,
    QUALITY_OPTIONS_BY_PROFILE,
    QUALITY_STANDARD,
    QUALITY_TARGET_LONG_EDGES,
    SizeOption,
    parse_pixel_size,
)
from output_quality import (
    QUALITY_LABELS,
    QUALITY_OPTIONS,
    available_quality_options,
    default_quality as _default_quality,
    infer_output_profile_id,
    is_supported_quality,
    normalize_output_profile_id,
    normalize_quality,
    quality_label,
)
from output_size import (
    available_size_options,
    default_size_for_quality,
    floor_to_multiple as _floor_to_multiple,
    infer_aspect_from_size as _infer_aspect_from_size,
    infer_quality_from_size,
    is_supported_size_option,
    is_supported_size_value,
    normalize_size_option,
    normalize_size_value,
    resolve_api_dimensions as _resolve_api_dimensions,
    resolve_api_size_value,
    resolve_openai_sdk_quality,
    resolve_openai_sdk_size_value,
    size_label,
    size_lookup_quality as _size_lookup_quality,
)
